apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: hello-world
build:
  artifacts:
    - image: hello-world
      docker:
        dockerfile: Dockerfile

    # to build from a M1 mac, change from docker build to this:
    # TODO: find a better way.
    # custom:
    #   buildCommand: docker buildx build  --platform linux/amd64 --tag $IMAGE  --push $BUILD_CONTEXT

deploy:
  kubectl:
    manifests:
      - k8s/web.yaml
