apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: hello-world
build:
  artifacts:
    - image: hello-world
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/web.yaml
